app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('students.urls', 'students'), namespace='students')),
]

students/urls.py
from django.urls import path
from .views import EstudianteView, DetailView
from django.contrib.auth import views as auth_views
from . import views


urlpatterns =[
    path('materia_notas_reprobadas/', views.materia_notas_reprobadas, name='materia_notas_reprobadas'),
    path('', EstudianteView.as_view(), name='estudiantes_list'),
    path('details/<int:pk>', DetailView.as_view(), name='estudiantes_detail'),
    path('desercion/', views.desercion, name='desercion' ),
    path('desercion_ciudades/', views.view_deserciones_por_ciudad, name='desercion_ciudades' ),
    path('view_estudiantes_por_materia/', views.view_estudiantes_por_materia, name='estudiantes_materia'),
    path('login/', auth_views.LoginView.as_view(template_name='base/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='base/login.html'), name="logout"),
]

students/models.py
from django.db import models


class Ciudad(models.Model):
     ciudad = models.CharField(max_length=255) 


     def __str__(self) -> str:
         return self.ciudad   


class Estudiante(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255, blank=False, null=False)
    identificacion = models.PositiveIntegerField(blank=False, null=False)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)


    def __str__(self):
        return self.nombre


class Ciclo(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255, blank=False, null=False)


    def __str__(self):
        return self.nombre


class Materia(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255, blank=False, null=False)
    ciclo = models.ForeignKey(Ciclo, on_delete=models.CASCADE, related_name='materias')


    def __str__(self):
        return self.nombre


class Periodo(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255, blank=False, null=False)


    def __str__(self):
        return self.nombre


class Nota(models.Model):
    id = models.AutoField(primary_key=True)
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE, related_name='notas')
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE, related_name='notas')
    periodo = models.ForeignKey(Periodo, on_delete=models.CASCADE, related_name='notas')
    nota = models.FloatField(blank=False, null=False)


    def __str__(self):
        return f'{self.estudiante} - {self.materia} - {self.nota}'



opciones_aprobado =[
    (1, 'si'),
    (2, 'no'),
]

class Resultado(models.Model):
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    desercion = models.IntegerField(null=False, blank=False, choices=opciones_aprobado, default=1)
    
    def __str__(self) -> str:
        return str(self.desercion)

students/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .models import Estudiante, Nota, Ciudad, Resultado, Materia
from django.db.models import Count
from django.db.models.functions import Coalesce
from django.db.models import Count, Q
import json


#class for Listview page home 
class EstudianteView(LoginRequiredMixin, generic.ListView):
    model = Estudiante
    template_name = 'bases/home.html'
    context_object_name = 'estudiante'
    login_url = 'students:login'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['estudiantes_count'] = Estudiante.objects.count()
        context['deserciones_count'] = Resultado.objects.filter(desercion=2).count()
        context['ciudades_count'] = Ciudad.objects.count()
        return context

    

#class for detailView for students 
class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Estudiante
    template_name = 'detail.html'
    context_object_name = 'estudiante'
    login_url = 'students:login'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['notas'] = Nota.objects.filter(estudiante=self.object)
        return context


def desercion(request):
    results = Resultado.objects.filter(desercion=2).select_related('estudiante__ciudad')
    estudiantes = [result.estudiante for result in results]
    context = {
        'estudiantes': estudiantes,
    }
    return render(request, 'desercion.html', context)


def view_deserciones_por_ciudad(request):
    results = Resultado.objects.filter(desercion=2) \
        .values('estudiante__ciudad__ciudad') \
        .annotate(deserciones=Count('estudiante__ciudad__ciudad'))

    context = {
        'deserciones': results,
    }
    return render(request, 'desercion_ciudad.html', context)


def view_estudiantes_por_materia(request):
    resultados = Materia.objects.annotate(num_estudiantes=Count('notas__estudiante', distinct=True))
    labels = [resultado.nombre for resultado in resultados]
    data = [resultado.num_estudiantes for resultado in resultados]

    context = {
        'labels': labels,
        'data': data,
    }
    return render(request, 'estudiantes_por_materia.html', context)


# materias con alumnos reprobados

def materia_notas_reprobadas(request):
    notas_reprobadas = Nota.objects.filter(nota__lt=5).values('materia__nombre').annotate(cantidad=Count('id')).order_by('-cantidad')[:10]
    labels = [nota['materia__nombre'] for nota in notas_reprobadas]
    data = [nota['cantidad'] for nota in notas_reprobadas]

    context = {
        'labels': labels,
        'data': data
    }

    return render(request, 'materia_notas_reprobadas.html', context)

bases/templates/bases/home.html
{% extends 'base/base.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card bg-gradient-success" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title text-center text-white">Estudiantes registrados</h5>
                  <div class="conteo text-center text-white">
                      <h1>{{ estudiantes_count }}</h1>
                  </div>
                </div>
              </div>
        </div>
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card bg-gradient-danger" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title text-center text-white">Posibles deserciones</h5>
                  <div class="conteo text-center text-white">
                    <h1>{{ deserciones_count }}</h1>
                </div>
                </div>
              </div>
        </div>
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body bg-gradient-info">
                  <h5 class="card-title text-center text-white">Ciudades</h5>
                  <div class="conteo text-center text-white">
                    <h1>{{ ciudades_count }}</h1>
                  </div>
                </div>
              </div>
        </div>
        
    </div>
</div>

<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div
        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-success">Listado de Estudiantes</h6>
        
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not estudiante %}
            No hay categorias disponibles
        {% endif %}
         <table class="table table-striped  table-hover">
            <thead>
                <th>Id</th>
                <th>Nombre</th>
                <th>Identificacion</th>
                <th>Ver Notas</th>
                
            </thead>

            <tbody>
                {% for item in estudiante %}
                    <tr>
                        <td>{{ item.id}}</td>
                        <td>{{ item.nombre}}</td>
                        <td>{{ item.identificacion}}</td>
                        
                        <td>
                            <a href="{% url 'students:estudiantes_detail' item.id %}" class="btn btn-success btn-circle" role="button"><i class="far fa-eye"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>

         </table>
    </div>
</div>

{% endblock content %}


{% block js_page %}
<script>
    //call datatables jquery plugin
    $(document).ready(function(){
        $('.table').DataTable();
    });
</script>

{% endblock js_page %}

students/templates/desercion.html
{% extends 'base/base.html' %}

{% block content %}

<div class="container">
    <div class="titulo text-center">
        <h1>Desercion por ciudad</h1>
        {% for estudiante in estudiantes %}
        <p>Estudiante: {{ estudiante.nombre }}</p>
        <p>Ciudad: {{ estudiante.ciudad.ciudad }}</p>
        {% endfor %}
    </div>
</div>

{% endblock content %}




{% block js_page %}

{% endblock js_page %}  

students/templates/desercion_ciudad.html
{% extends 'base/base.html' %}

{% block content %}

<div class="container">
    <div class="title text-center">
        <h1>Deserciones por ciudades</h1>
    

    <div class="row mt-4">
        <div class="col">
            <canvas id="pieChart"></canvas>
        </div>

    </div>

</div>

{% endblock %}

{% block js_page %}

<script>
    var ctx = document.getElementById('pieChart').getContext('2d');
    var pieChart = new Chart(ctx, {
      type: 'pie',
      data: {
        labels: [{% for desercion in deserciones %} '{{ desercion.estudiante__ciudad__ciudad }}', {% endfor %}],
        datasets: [{
          label: 'Deserciones por ciudad',
          data: [{% for desercion in deserciones %} {{ desercion.deserciones }}, {% endfor %}],
          backgroundColor: [
            'rgba(255, 99, 132, 1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 1)',
            'rgba(255, 159, 64, 1)'
          ],
          borderColor: [
            'rgba(255, 99, 132, 1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 1)',
            'rgba(255, 159, 64, 1)'
          ],
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true
            }
          }]
        }
      }
    });
  </script>
  

{% endblock js_page %}

students/templates/detail.html
{% extends 'base/base.html' %}

{% block content %}

<div class="container">
    <div class="titulo text-center">
        <h1>Notas de  {{ estudiante.nombre }}</h1>
    </div>
    <div class="row mt-4">
        <div class="col">
            <canvas id="myChart"></canvas>

        </div>

    </div>
    <div class="container text-center mt-5">
        <a href="{% url 'students:estudiantes_list' %}" class="btn btn-success" role="button">Volver al listado</a>

    </div>


</div>

{% endblock content %}

{% block js_page %}
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [
                {% for nota in notas %}
                '{{ nota.materia.nombre }}',
                {% endfor %}
            ],
    datasets: [{
        label: 'Notas',
        data: [
            {% for nota in notas %}
                    {{ nota.nota }},
    {% endfor %}
    ],
        backgroundColor: [
            'rgba(255, 99, 132, 1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 1)',
            'rgba(255, 159, 64, 1)',
            'rgba(255, 99, 132, 1)'
        ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)',
                'rgba(255, 99, 132, 1)'
            ],
                borderWidth: 1
            }]
        },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
    });
</script>


{% endblock js_page %}

students/templates/estudiantes_por_materia.html
{% extends 'base/base.html' %}


{% block content %}


<div class="container">
    <div class="title text-center">
        <h1>Estudiantes por materias</h1>
    

    <div class="row mt-4">
        <div class="col">
            <canvas id="estudiantes-por-materia-chart"></canvas>
        </div>

    </div>

</div>
  
  

  <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.0"></script>
  <script>
    const labels = {{ labels|safe }};
    const data = {{ data|safe }};

    const ctx = document.getElementById('estudiantes-por-materia-chart').getContext('2d');
    const chart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: labels,
        datasets: [{
          label: 'Estudiantes por materia',
          data: data,
          backgroundColor: 'rgba(54, 162, 235, 0.2)',
          borderColor: 'rgba(54, 162, 235, 1)',
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  </script>
{% endblock %}

students/templates/materia_notas_reprobadas.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="text-center m-4">Materias con mayores reprobados</h1>
    <canvas id="myChart"></canvas>
</div>


<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: {{ labels|safe }},
            datasets: [{
                label: 'Notas reprobadas por materia',
                data: {{ data|safe }},
                backgroundColor: 'rgba(255, 99, 132, 1)',
                borderColor: 'rgba(255, 99, 132, 1)',
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
</script>
{% endblock %}

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Students app</title>

    <!-- Custom fonts for this template-->
    <link href="{% static  'base/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static 'base/css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

    <!-- iclude chart.js para el grafico -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

</head>

<body id="page-top">
    {% block side_bar %}
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'students:estudiantes_list' %}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class=""></i>  
                </div>
                <div class="sidebar-brand-text mx-3">Students Admin</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'students:estudiantes_list' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'students:desercion_ciudades' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Desercion por ciudades</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'students:estudiantes_materia' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Estudiantes por materia</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'students:materia_notas_reprobadas' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Materias con mayores reprobados</span></a>
            </li>

            
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        {% endblock side_bar %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                {% block top_bar %}

                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        
                      

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                                <img class="img-profile rounded-circle" src="static/base/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'students:logout' %}" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Salir
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                {% endblock top_bar %}
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                
                {% block content %}
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Notas</h1>

                </div>
                {% endblock content %}
                <!-- /.container-fluid -->
                {% block footer %}
            </div>
            <!-- End of Main Content -->
            
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Juan David 2023</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    {% endblock footer %}
    <!-- End of Page Wrapper -->
    {% block login %} {% endblock login %}
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'students:logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'base/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'base/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'base/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>



    {% block js_page %} {% endblock js_page %}
</body>

</html>

templates/base/login.html
{% extends "base/base.html" %}

{% block side_bar %} {% endblock %}
{% block top_bar %} {% endblock %}
{% block content %} {% endblock %}
{% block footer %} {% endblock %}

{% block login %}

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Bienvenido de nuevo!</h1>
                                    <small class="text-danger">
                                        {% if form.errors %}
                                            {% for field in form %}
                                                {% if field.errors %}
                                                {% for error in field.errors %}
                                                   {{ error|escape }}
                                                {% endfor %}
                                                {% endif %}
                                            {% endfor %}


                                        {% if form.non_field_errors %}
                                            {% for error in form.non_field_errors %}
                                            {{ error|escape }}
                                            {% endfor %}
                                        {% endif %}
                                        {% endif %}
                                    </small>
                                </div>
                                <form class="user" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="text" class="form-control form-control-user"
                                            name="username"
                                            id="id_username" aria-describedby="emailHelp"
                                            placeholder="nombre de usuario">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control form-control-user"
                                            name="password"
                                            id="id_password" placeholder="Contraseña">
                                    </div>                              
                                    
                                     
                                    <button type="submit" class="btn btn-primary btn-user btn-block">
                                        Acceder
                                    </button>
                                </form>
                                <div class="text-center">
                                    <a class="small" href="forgot-password.html">Olvidaste tu password ?</a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="register.html">Crear una cuenta!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock login %}